/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testEncryptSimple1() {
        // Limitation: difficult to make work with special characters, so using a subset of common characters
        CaesarCipher classUnderTest = new CaesarCipher();
        int e = 1;
        String m = "abcdefghijklmnopqrstuvwxyz1234567890 ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        String c = "bcdefghijklmnopqrstuvwxyz{23456789:1!BCDEFGHIJKLMNOPQRSTUVWXYZ[";
        assertEquals(c,classUnderTest.encrypt(m,e));
    }

    @Test
    public void testDecryptSimple1() {
        // Limitation: difficult to make work with special characters, so using a subset of common characters
        CaesarCipher classUnderTest = new CaesarCipher();
        int e = 1;
        String c = "bcdefghijklmnopqrstuvwxyz{23456789:1!BCDEFGHIJKLMNOPQRSTUVWXYZ[";
        String m = "abcdefghijklmnopqrstuvwxyz1234567890 ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        assertEquals(m,classUnderTest.decrypt(c,e));
    }
    @Test
    public void testRecovery() {
        CaesarCipher classUnderTest = new CaesarCipher();
        String m = "abcdefghijklmnopqrstuvwxyz1234567890 ABCDEFGHIJKLMNOPQRSTUVWXYZ!@#$%^&*()`-=[]\\;',./~_+{}|:\"<>?";
        for (int e = 1; e < 30; e++) {
            String c = classUnderTest.encrypt(m,e);
            assertNotEquals(m,c); // After encryption, the cipher text should not match the plain text
            String d = classUnderTest.decrypt(c,e);
            assertEquals(m,d); // The decrypted cipher text should match the original plain text
        }
    }
}